#[derive(Clone, Copy)]
pub(crate) enum LogicalKey {
    Shift,
    Control,
    Alt,
    Super,
    Return,
    BackSpace,
    Tab,
    Escape,
    Space,
    Up,
    Down,
    Left,
    Right,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,
    Print,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Char(char),
}

impl LogicalKey {
    pub(crate) fn parse(name: &str) -> Option<Self> {
        use LogicalKey::*;
        Some(match name.to_lowercase().as_str() {
            "shift" => Shift,
            "ctrl" | "control" => Control,
            "alt" => Alt,
            "win" | "super" | "meta" => Super,
            "enter" | "return" => Return,
            "backspace" => BackSpace,
            "tab" => Tab,
            "esc" | "escape" => Escape,
            "space" => Space,
            "up" => Up,
            "down" => Down,
            "left" => Left,
            "right" => Right,
            "home" => Home,
            "end" => End,
            "pageup" => PageUp,
            "pagedown" => PageDown,
            "insert" => Insert,
            "delete" => Delete,
            "printscreen" => Print,
            "f1" => F1,
            "f2" => F2,
            "f3" => F3,
            "f4" => F4,
            "f5" => F5,
            "f6" => F6,
            "f7" => F7,
            "f8" => F8,
            "f9" => F9,
            "f10" => F10,
            "f11" => F11,
            "f12" => F12,
            s if s.chars().count() == 1 => Char(s.chars().next()?),
            _ => return None,
        })
    }
}
